<a href="https://colab.research.google.com/github/gitconnoisseur/toxicity-model/blob/master/ecfp_xgb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install PyTDC
!pip install deepchem
!pip install autokeras
!pip install --upgrade numpy

In [1]:
#import autogluon as ag
from tdc.single_pred import Tox
import deepchem
import xgboost

import numpy as np
import pandas as pd
import tensorflow as tf
import autokeras as ak

from tdc.benchmark_group import admet_group
group = admet_group(path = 'data/')

Found local copy...


In [3]:
predictions_list = []
metric = deepchem.deepchem.metrics.Metric(deepchem.deepchem.metrics.mean_absolute_error)

for seed in [1, 2, 3, 4, 5]:
    benchmark = group.get('LD50_Zhu') 
    # all benchmark names in a benchmark group are stored in group.dataset_names
    predictions = {}
    name = benchmark['name']
    train_val, test = benchmark['train_val'], benchmark['test']
    train, valid = group.get_train_valid_split(benchmark = name, split_type = 'default', seed = seed)
    
        # --------------------------------------------- # 
        #  Train your model using train, valid, test    #
        #  Save test prediction in y_pred_test variable #
        # --------------------------------------------- #
    

    featurizer = deepchem.deepchem.feat.WeaveFeaturizer()
    f_train = featurizer.featurize(train.iloc[:,1].to_list())
    f_valid = featurizer.featurize(valid.iloc[:,1].to_list())

    train_data = deepchem.deepchem.data.NumpyDataset(X=f_train, y=np.array(train.iloc[:,2]), ids=np.array(train.iloc[:,1].to_list()))
    valid_data = deepchem.deepchem.data.NumpyDataset(X=f_valid, y=np.array(valid.iloc[:,2]), ids=np.array(valid.iloc[:,1].to_list()))

    reg = deepchem.deepchem.models.WeaveModel(n_tasks=1, mode="regression", n_hidden=300, n_weave=4, fully_connected_layer_sizes=[2000, 1000, 100], batch_normalize_kwargs={"trainable": False})
    callback = deepchem.deepchem.models.ValidationCallback(valid_data, 1000, metric)
    reg.fit(train_data, nb_epoch=100, callbacks=callback)

    testFeatures = np.array(featurizer.featurize(test.iloc[:,1].to_list()))

    y_pred_test = reg.predict_on_batch(X=testFeatures)

    print("predictions for run #")
    print(seed)
    print(y_pred_test[0:5])
        
    predictions[name] = y_pred_test
    predictions_list.append(predictions)

print("Prediction List:")
print(predictions_list)

generating training, validation splits...
100%|██████████| 5907/5907 [00:01<00:00, 3482.04it/s]


Step 1000 validation: mean_absolute_error=0.565831
Step 2000 validation: mean_absolute_error=0.563365
Step 3000 validation: mean_absolute_error=0.550887
Step 4000 validation: mean_absolute_error=0.588457
Step 5000 validation: mean_absolute_error=0.549276


generating training, validation splits...


predictions for run #
1
[[2.2228622]
 [3.1631806]
 [3.1934752]
 [3.6838799]
 [4.0056653]]


100%|██████████| 5907/5907 [00:01<00:00, 3614.00it/s]


Step 1000 validation: mean_absolute_error=0.635256
Step 2000 validation: mean_absolute_error=0.579254
Step 3000 validation: mean_absolute_error=0.555295
Step 4000 validation: mean_absolute_error=0.54472
Step 5000 validation: mean_absolute_error=0.574102


generating training, validation splits...


predictions for run #
2
[[2.1847672]
 [2.652504 ]
 [2.5819736]
 [2.8940196]
 [3.0502727]]


100%|██████████| 5907/5907 [00:01<00:00, 4641.75it/s]


Step 1000 validation: mean_absolute_error=0.615951
Step 2000 validation: mean_absolute_error=0.765253
Step 3000 validation: mean_absolute_error=0.616547
Step 4000 validation: mean_absolute_error=0.609268


generating training, validation splits...


predictions for run #
3
[[1.9476023]
 [2.808782 ]
 [3.2775142]
 [3.45166  ]
 [3.5136507]]


100%|██████████| 5907/5907 [00:01<00:00, 4566.62it/s]


Step 1000 validation: mean_absolute_error=0.604719
Step 2000 validation: mean_absolute_error=0.579928
Step 3000 validation: mean_absolute_error=0.589344
Step 4000 validation: mean_absolute_error=0.621545
Step 5000 validation: mean_absolute_error=0.556923


generating training, validation splits...


predictions for run #
4
[[2.2946644]
 [2.6160471]
 [2.4256215]
 [2.742159 ]
 [2.8800755]]


100%|██████████| 5907/5907 [00:01<00:00, 4025.11it/s]


Step 1000 validation: mean_absolute_error=0.587477
Step 2000 validation: mean_absolute_error=0.600091
Step 3000 validation: mean_absolute_error=0.509169
Step 4000 validation: mean_absolute_error=0.51635
predictions for run #
5
[[1.5845625]
 [2.7674878]
 [2.931089 ]
 [3.3199785]
 [3.56302  ]]
Prediction List:
[{'ld50_zhu': array([[2.2228622],
       [3.1631806],
       [3.1934752],
       ...,
       [2.171519 ],
       [1.986639 ],
       [2.1971977]], dtype=float32)}, {'ld50_zhu': array([[2.1847672],
       [2.652504 ],
       [2.5819736],
       ...,
       [2.3386254],
       [2.4158752],
       [2.069726 ]], dtype=float32)}, {'ld50_zhu': array([[1.9476023],
       [2.808782 ],
       [3.2775142],
       ...,
       [1.9402995],
       [1.926537 ],
       [2.0397625]], dtype=float32)}, {'ld50_zhu': array([[2.2946644],
       [2.6160471],
       [2.4256215],
       ...,
       [1.9778394],
       [1.942879 ],
       [1.9425211]], dtype=float32)}, {'ld50_zhu': array([[1.5845625],
    

In [4]:
for i in predictions_list:
    print(group.evaluate(i))

group.evaluate_many(predictions_list)

{'ld50_zhu': {'mae': 0.687}}
{'ld50_zhu': {'mae': 0.707}}
{'ld50_zhu': {'mae': 0.709}}
{'ld50_zhu': {'mae': 0.781}}
{'ld50_zhu': {'mae': 0.703}}


{'ld50_zhu': [0.717, 0.033]}

In [6]:
# multiply mae by negative one so it can be maximized
hyperOptMetric = deepchem.deepchem.metrics.Metric(lambda *args: -1.0 * deepchem.deepchem.metrics.mean_absolute_error(*args), mode="regression")

def model_builder(**model_params):
  return deepchem.deepchem.models.WeaveModel(n_tasks=1, mode="regression", batch_normalize_kwargs={"trainable": False})

#optimizer = deepchem.deepchem.hyper.GaussianProcessHyperparamOpt(model_builder)

optimizer = deepchem.deepchem.hyper.GaussianProcessHyperparamOpt(model_builder)

params_dict = {"n_pair_feat": 14, "n_hidden": 50}

best_model, best_hyperparams, all_results = optimizer.hyperparam_search(params_dict, train_data, valid_data, hyperOptMetric, search_range=5)

Evaluation 	 Proposed point 	  Current eval. 	 Best eval.


init   	 [130. 329.  17.]. 	  -0.7555424053672201 	 -0.6375722658437386
init   	 [  4. 285.  17.]. 	  -0.6375722658437386 	 -0.6375722658437386
init   	 [ 48. 364.   7.]. 	  -0.7049368234474378 	 -0.6375722658437386


1      	 [137.  40.   4.]. 	  -0.6186904076187795 	 -0.6186904076187795


2      	 [ 38. 448.   3.]. 	  -0.5716399556767795 	 -0.5716399556767795


3      	 [ 73. 401.  19.]. 	  -0.5750580500485288 	 -0.5716399556767795


4      	 [ 67. 306.  14.]. 	  -0.5769406830009493 	 -0.5716399556767795


5      	 [ 4. 21.  0.]. 	  -0.5816318836108919 	 -0.5716399556767795


6      	 [ 25. 277.   1.]. 	  -0.5791916413429787 	 -0.5716399556767795


KeyboardInterrupt: 